/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>
#include <system_stm32f4xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  SystemCoreClockUpdate();
  SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
  SET_BIT(GPIOC->MODER, GPIO_MODER_MODE9_1);
  SET_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR9);

  SET_BIT(RCC->CFGR, RCC_CFGR_MCO2PRE_0);
  SET_BIT(RCC->CFGR, RCC_CFGR_SW_HSI);

    /* Loop forever */
	for(;;);
}
