/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>
#include <system_stm32f4xx.h>
#include <stm32f4xx_ll_utils.h>
#include <stm32f4xx_ll_usart.h>
#include <stm32f4xx_ll_gpio.h>
#include <stm32f4xx_ll_bus.h>

static void inline ll_init_usart2()
{
	LL_GPIO_InitTypeDef u2_tx, u2_rx;
	LL_USART_InitTypeDef usart2;

	/* Init PA2 as Tx & PA3 as Rx for USART2*/
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);
	LL_GPIO_StructInit(&u2_tx);
	u2_tx.Pin 		= LL_GPIO_PIN_2;
	u2_tx.Mode 		= LL_GPIO_MODE_ALTERNATE;
	u2_tx.Alternate = LL_GPIO_AF_7;
	LL_GPIO_Init(GPIOA, &u2_tx);

	LL_GPIO_StructInit(&u2_rx);
	u2_rx.Pin 		= LL_GPIO_PIN_3;
	u2_rx.Mode 		= LL_GPIO_MODE_ALTERNATE;
	u2_rx.Alternate = LL_GPIO_AF_7;
	LL_GPIO_Init(GPIOA, &u2_rx);

	/* Init USART2*/
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_USART2);
	LL_USART_StructInit(&usart2);
	LL_USART_Init(USART2, &usart2);
	LL_USART_Enable(USART2);

	/* Set priority */
	NVIC_EnableIRQ(USART2_IRQn);
	LL_USART_EnableIT_RXNE(USART2);
}

static inline void HSI_oscilator()
{
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
    SET_BIT(GPIOC->MODER, GPIO_MODER_MODE9_1);
    SET_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR9);

    SET_BIT(RCC->CFGR, RCC_CFGR_MCO2PRE_0);
    SET_BIT(RCC->CFGR, RCC_CFGR_SW_HSI);
    CLEAR_BIT(RCC->CFGR, RCC_CFGR_MCO2_0 | RCC_CFGR_MCO2_1);
}

static inline void HSE_oscilator()
{
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
    SET_BIT(GPIOC->MODER, GPIO_MODER_MODE9_1);
    SET_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR9);

    SET_BIT(RCC->CFGR, RCC_CFGR_MCO2PRE_0);
    CLEAR_BIT(RCC->CFGR, RCC_CFGR_MCO2PRE_1);

    SET_BIT(RCC->CFGR, RCC_CFGR_SW_HSI);

    SET_BIT(RCC->CFGR, RCC_CFGR_MCO2_1);
    CLEAR_BIT(RCC->CFGR, RCC_CFGR_MCO2_0);

    SET_BIT(RCC->CR, RCC_CR_HSEON);
    while(READ_BIT(RCC->CR, RCC_CR_HSERDY) == 0);
}

/* Check for the correct PLL configuration values */
static inline void PLL_oscilator() {
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
    SET_BIT(GPIOC->MODER, GPIO_MODER_MODE9_1);
    SET_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR9);

    // Always set HSI a System Clock Source
    SET_BIT(RCC->CFGR, RCC_CFGR_SW_HSI);
    // Enable HSE
    SET_BIT(RCC->CR, RCC_CR_HSEON);

    // Wait till HSE is ready
    while(READ_BIT(RCC->CR, RCC_CR_HSERDY) == 0);

    // Set the PLL source to HSE
    SET_BIT(RCC->PLLCFGR, RCC_PLLCFGR_PLLSRC_HSE);

    // Set the PLL multiplication and division factors
    // Example: Set PLLN to 192, PLLM to 8 and PLLP to 8
    // f_PLL = CLK_Source * PLLN / (PLLM * PLLP)
    MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLN, 192 << RCC_PLLCFGR_PLLN_Pos); // PPLN = 198
    MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLM, 8 << RCC_PLLCFGR_PLLM_Pos); // PLLM = 8
    MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLP, 3 << RCC_PLLCFGR_PLLP_Pos); // PLLP = 8

    // Enable the PLL
    SET_BIT(RCC->CR, RCC_CR_PLLON);

    // Wait till PLL is ready
    while(READ_BIT(RCC->CR, RCC_CR_PLLRDY) == 0);

    // Set the MCO2 clock source to PLL and prescaler
    SET_BIT(RCC->CFGR, RCC_CFGR_MCO2_0 | RCC_CFGR_MCO2_1);
    CLEAR_BIT(RCC->CFGR, RCC_CFGR_MCO2PRE_0 | RCC_CFGR_MCO2PRE_1 | RCC_CFGR_MCO2PRE_2);
}

int main(void)
{
    SystemCoreClockUpdate();
    LL_Init1msTick(SystemCoreClock);
    ll_init_usart2();

    /* Loop forever */
  	for(;;)
    {
        HSI_oscilator();
        LL_mDelay(10000);
        HSE_oscilator();
        LL_mDelay(10000);
        PLL_oscilator();
        LL_mDelay(10000);
    }
}
